package com.javacode.ws.client;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name="WebServiceImplService", targetNamespace="http://server.ws.javacode.com/", wsdlLocation="http://localhost:8888/ws/helloworld?wsdl")
public class WebServiceImplService extends Service {
    private final static URL WEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICE_EXCEPTION;
    private final static QName WEBSERVICE_QNAME = new QName("http://server.ws.javacode.com/", "WebServiceImplService");

    static {
        URL url = null;
        WebServiceException exception = null;
        try {
            url = new URL("http://localhost:8888/ws/helloworld?wsdl");
        } catch (MalformedURLException ex) {
            exception = new WebServiceException(ex);
        }
        WEBSERVICE_WSDL_LOCATION = url;
        WEBSERVICE_EXCEPTION = exception;
    }

    public WebServiceImplService() {
        super(__getWsdlLocation(), WEBSERVICE_QNAME);
    }

//    public WebServiceImplService(WebServiceFeature... features) {
//        super(__getWsdlLocation(), WEBSERVICE_QNAME, features);
//    }
//
//    public WebServiceImplService(URL wsdlLocation) {
//        super(wsdlLocation, WEBSERVICE_QNAME);
//    }
//
//    public WebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
//        super(wsdlLocation, WEBSERVICE_QNAME, features);
//    }
//
//    public WebServiceImplService(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }
//
//    public WebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     * @return
     *     returns WebServiceInterface
     */
    @WebEndpoint(name="WebServiceImplPort")
    public WebServiceInterface getWebServiceImplPort() {
        return super.getPort(new QName("http://server.ws.javacode.com/", "WebServiceImplPort"), WebServiceInterface.class);
    }

    /**
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceInterface
     */
    @WebEndpoint(name="WebServiceImplPort")
    public WebServiceInterface getWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.ws.javacode.com/", "WebServiceImplPort"), WebServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICE_EXCEPTION != null) throw WEBSERVICE_EXCEPTION;
        return WEBSERVICE_WSDL_LOCATION;
    }

}
